{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "release-name" . }}
  namespace : {{ include "namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "release-name" . }}
    release: {{ include "release-name" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.isHeadLess }}
  clusterIP: None
  {{- end }}
  {{- if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  {{- range $name, $config := .Values.ports }}
  - name: {{ $name }}
    port: {{ $config.port }}
    targetPort: {{ $config.targetPort }}
    {{- if eq $.Values.service.type "NodePort" }}
    nodePort: {{ $config.nodePort }}
    {{- end }}
    protocol: {{ default "TCP" $config.protocol | quote }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "release-name" . }}
    release: {{ include "release-name" . }}
{{- end }}
