apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubernetes.io/change-cause: charts for Geektime p8 homework
    meta.helm.sh/release-name: httpdemo
    meta.helm.sh/release-namespace: apisix
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: httpdemo
    release: httpdemo
  name: httpdemo
  namespace: apisix
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  revisionHistoryLimit: 7
  selector:
    matchLabels:
      app.kubernetes.io/name: httpdemo
      release: httpdemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpdemo
        release: httpdemo
      name: httpdemo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - httpdemo
                - key: release
                  operator: In
                  values:
                  - httpdemo
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: httpdemo:v1.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - sleep
              - "1"
          preStop:
            exec:
              command:
              - sleep
              - "1"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8081
          timeoutSeconds: 3
        name: httpdemo
        ports:
        - containerPort: 8081
          name: app
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8081
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 300m
            ephemeral-storage: 2Gi
            memory: 500Mi
          requests:
            cpu: 100m
            ephemeral-storage: 1Gi
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/work/data
          name: data-volume
        - mountPath: /home/work/conf
          name: conf-volume
        - mountPath: /home/work/logs
          name: logs-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - {}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: environment
        operator: Equal
        value: production
      volumes:
      - emptyDir: {}
        name: data-volume
      - emptyDir: {}
        name: conf-volume
      - emptyDir: {}
        name: logs-volume