apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: httpdemo
    meta.helm.sh/release-namespace: apisix
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: httpdemo
    release: httpdemo
  name: httpdemo
  namespace: apisix
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: app
    nodePort: 31889
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: httpdemo
    release: httpdemo
  sessionAffinity: None
  type: NodePort